[build]
builder = "NIXPACKS"
buildCommand = "npm ci"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "3000"
NODE_VERSION = "18"

# Force Node.js detection
NIXPACKS_NODE_VERSION = "18"

# Railway will read from project environment variables
# Make sure to set these in Railway dashboard:
# GEMINI_API_KEY
# COHERE_API_KEY
# VITE_SUPABASE_URL
# VITE_SUPABASE_KEY
# VITE_SUPABASE_ANON_KEY
# DIFFBOT_TOKEN
# FOREX_API2_RAPIDAPI_KEY
# VITE_RAPIDAPI_KEY
# ECONOMIC_CALENDAR_RAPIDAPI_KEY
# FINNHUB_API_KEY
# FMP_API_KEY
# MBOUM_RAPIDAPI_KEY
